### PR TITLE
Add gradle wrapper

### PR DESCRIPTION
**Pull request by zhurlik**
I have added gradlew to be able to use it how it was mentioned in the [issue#8](https://github.com/OpenLiberty/guide-gradle-intro/issues/8)

### CODE REVIEW

**Comment by gkwan-ibm** [comment]
hi @zhurlik, 

Thank you for your contribution.

Did you sign the [Individual Contributor License Agreement](https://github.com/OpenLiberty/open-liberty/blob/master/cla/open-liberty-cla-individual.pdf) (ICLA) or [Corporate Contributor License Agreement](https://github.com/OpenLiberty/open-liberty/blob/master/cla/open-liberty-cla-corporate.pdf) (CCLA)? If not and you want to contribute the change, would you sign either ICLA or CCLA? Instructions how to sign and submit these agreements are located at the top of each document. 

After we obtain the signed CLA, we will review and verify the change. If the result is satisfied, this PR will be merged, otherwise this PR will be closed with an explanation and suggestion for followup.

Thanks

**Comment by zhurlik** [comment]
@gkwan-ibm Thank you for your quick response. I just have sent my ICLA file to cla@openliberty.io

**Comment by zhurlik** [comment]
Just now I have got the mail from Harry Hoots that my CLA request has been processed

**Comment by gkwan-ibm** [comment]
@zhurlik We are starting to verify and review your change.

**Comment by evelinec** [comment]
Checked that @DannyS03 had done testing on 3 platforms. FYI @gkwan-ibm

**Pull request merged**
